on:
  workflow_dispatch:

jobs:
  bar:
    runs-on: ubuntu-latest
    steps:
    - run: gh api /repos/robinjam-test-org/dependabot-auto-merger/actions/workflows/foo.yml/dispatches --input - <<< '{"ref":"master","inputs":{"foo":"This is a test"}}'
